apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:1.26
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "10Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
