apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nginx:1.26
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "10Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
