apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: bootcamp-sdso-ksa
      containers:
        - name: backend
          image: aryyadocker/bootcamp-sdso-backend
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "10Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
          stdin: true
          stdinOnce: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: "/var/secrets"
              name: mysecret
      volumes:
      - name: mysecret
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: bootcamp-sdso-secret-provider
