apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
        - name: backend
          image: aryyadocker/bootcamp-sdso-backend
          envFrom:
            - configMapRef:
                name: backend-config
          env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: gke-cloud-sql-secrets
                key: host
          - name: INSTANCE_CONNECTION_NAME
            valueFrom:
              secretKeyRef:
                name: gke-cloud-sql-secrets
                key: instance_connection_name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: gke-cloud-sql-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gke-cloud-sql-secrets
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: gke-cloud-sql-secrets
                key: database
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "10Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
