configurations:
  - image-transformer.yaml
images:
  - name: aryyadocker/bootcamp-sdso-backend
    newTag: 67544019474c3d82384907028842867007df69e8
resources:
  - config-map.yaml
  - deployment.yaml
  - service.yaml
