configurations:
- image-transformer.yaml
images:
- name: aryyadocker/bootcamp-sdso-backend
  newTag: f437b3f1b2c09a472a3902f06c4f8e40e406f06a
resources:
- config-map.yaml
- deployment.yaml
- service.yaml
