apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
spec:
  destination:
    namespace: bootcamp-sdso
    server: https://kubernetes.default.svc
  source:
    path: database
    repoURL: https://github.com/aryyawijaya/bootcamp-sdso-k8s
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
