apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
spec:
  destination:
    name: ''
    namespace: bootcamp-sdso
    server: https://kubernetes.default.svc
  source:
    path: frontend
    repoURL: https://github.com/aryyawijaya/bootcamp-sdso-k8s.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
